title: "Santiago's Portfolio"
email: your-email@example.com
description: "A portfolio showcasing my projects in mathematics and modeling"
baseurl: ""
url: "https://santiagogr10.github.io"
twitter_username: your_twitter_handle  # optional
github_username: santiagogr10

# Build settings
theme: minima
plugins:
  - jekyll-feed
